trainingInput:
        scaleTier: CUSTOM
        masterType: complex_model_m_gpu
        workerType: complex_model_m_gpu
        parameterSeryverType: large_model
        workerCount: 9
        parameterServerCount: 3
